### ISSUE TITLE
Reduce prices for tools

### ISSUE THREAD

**Issue by peraldon** [IslesSoftworks/IslandClash-Issues#11]
Gold removed

**Comment by peraldon** [comment]
Stone: 20
Iron: 40
Diamond: 80

**Comment by Unknowncmbk** [comment]
@peraldon 
What should be purchasable at tier 1 logging camp?

**Comment by peraldon** [comment]
Just the wood at t1

**Comment by Unknowncmbk** [comment]
Wood: 2 (profit: 5)
Stone: 15 (profit: 7)
Iron: 25 (profit: 12)
Diamond: 75 (profit: 25)
